#!/usr/bin/env bash


# .git/hooks/pre-commit
: << !
#!/usr/bin/env bash
if [ -f ".githook" ]; then . ".githook"; fi
!


# eslint exists
eslint="./node_modules/.bin/eslint"
if [[ ! $(command -v $eslint) ]]; then
  eslint="eslint"
  if [[ ! $(command -v $eslint) ]]; then
    # npm i -g eslint
    echo -e "\033[31m  please install eslint: npm i -g eslint  \033[0m"
    exit 1
  fi
fi


# files
ext=".(js|jsx|ts|vue)$"
files=$(git diff --cached --name-only | egrep $ext)


# -deleted
for file in $files; do
  if [[ ! -f $file ]]; then
    files=$(echo "$files" | egrep -v "^$file$")
  fi
done


# has not files to eslint
if [[ ! $(echo "$files" | egrep "\w") ]]; then
  # echo "has not files to eslint"
  exit 0
fi


# fix
output=$($eslint $files --fix)
output=$($eslint $files --quiet --format visualstudio)
code=$?


# add again
git add $files


# color
output=${output//"error"/"\033[31merror\033[0m"}


# error exit?
if [[ $code != 0 ]]; then
  echo -e "$output"
  echo -e "\033[31m  ERROR  \033[0m"
  exit 1
fi
